# add stages here 
stages:
  load_data:
    cmd: python src/stage_01_load_save_data.py -c=configs/config.yaml
    deps:
    - src/stage_01_load_save_data.py
    - src/utils/common.py
    - configs/config.yaml
    outs:
    - artifacts/raw_local_dir/data.csv
