# It contains all the configs required in the project
datasource: http://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv

artifacts:
  ARTIFACTS_DIR: artifacts
  RAW_LOCAL_DIR: raw_local_dir
  RAW_LOCAL_FILE: data.csv
